<?php

namespace MP\TimeSheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssociateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociateRepository extends EntityRepository
{

    // find mission-associate from Mission id
    public function findAssociates($id)
    {
        $result = $this->createQueryBuilder('a')
            ->select('a')
            ->innerJoin('a.missions', 'm')
            ->where('m.id = :id')
            ->setParameter(':id', $id)
            ->getQuery()
            ->getResult();

        return $result;

    }


    public function findAssociate($id)
    {
        $result = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.id = :id')
            ->setParameter(':id', $id);

        return $result;
    }

    public function findNoMissionAssociates()
    {
        $result = $this->createQueryBuilder('a')
            ->select('DISTINCT a')
            ->leftJoin('a.missions', 'm')
            ->where('m.status != :st')
            ->orWhere('m.id is NULL')
            ->andWhere('a.post = :collab')
            ->setParameter(':collab', 'collaborateur')
            ->setParameter(':st', 'En cours');

        return $result;
    }

    public function findAllChiefs()
    {
        $result = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.missions', 'm')
            ->where('m.status != :st')
            ->orWhere('m.id is NULL')
            ->andWhere('a.post = :chief')
            ->setParameter(':chief', 'chef de mission')
            ->setParameter(':st', 'En cours');

        return $result;
    }

    public function findAllManagers()
    {
        $result = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.post = :man')
            ->setParameter(':man', 'manager');

        return $result;
    }

    public function findAllSignataries()
    {
        $result = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.post = :sig')
            ->setParameter(':sig', 'signataire');

        return $result;
    }

    public function findNoMissions()
    {
        $result = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.missions', 'm')
            ->Where('m.id is NULL');


        return $result;
    }
}
