<?php

namespace MP\TimeSheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AssociateMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociateMissionRepository extends EntityRepository
{
    public function findByAssociateMission($aid, $mid)
    {
        $result = $this->createQueryBuilder('am')
            ->where('am.associate = :aid')
            ->andWhere('am.mission = :mid')
            ->setParameter(':aid', $aid)
            ->setParameter(':mid', $mid)
            ->getQuery()
            ->getSingleResult();

        return $result;
    }
}
