<?php

namespace MP\TimeSheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findClientContact($id)
    {
        $result = $this->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter(':id', $id)
            ->leftJoin('c.mainContact', 'mC')
            ->addSelect('mC')
            ->getQuery()
            ->getSingleResult();

        return $result;
    }

    public function findAllClientContact()
    {
        $result = $this->createQueryBuilder('c')
             ->leftJoin('c.mainContact', 'mC')
            ->addSelect('mC')
            ->getQuery()
            ->getResult();

        return $result;
    }
}
