<?php

namespace MP\TimeSheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends EntityRepository
{

    // find all mission-associate
    public function findAllAssociates()
    {
        $result = $this->createQueryBuilder('m')
            ->select('m')
            ->leftJoin('m.associates', 'a')
            ->leftJoin('m.clients', 'c')
            ->addSelect('c')
            ->addSelect('a')
            ->getQuery()
            ->getResult();

        return $result;

    }

    // find the mission of an associate by its id
    public function findMissions($id)
    {
        $result = $this->createQueryBuilder('m')
            ->select('m')
            ->leftJoin('m.associates', 'a')
            ->where('a.id = :id')
            ->andWhere('m.status = :stat')
            ->setParameter(':stat', 'En cours')
            ->setParameter(':id', $id);

        return $result;
    }

    public function findOnGoing()
    {
        $result = $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.status = :stat')
            ->setParameter(':stat', 'En cours')
            ->leftJoin('m.associates', 'a')
            ->leftJoin('m.clients', 'c')
            ->addSelect('c')
            ->addSelect('a')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findCompleted()
    {
        $result = $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.status = :stat')
            ->setParameter(':stat', 'Terminée')
            ->leftJoin('m.associates', 'a')
            ->leftJoin('m.clients', 'c')
            ->addSelect('c')
            ->addSelect('a')
            ->getQuery()
            ->getResult();

        return $result;

    }

}
