<?php

namespace MP\TimeSheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeSheetRepository extends EntityRepository
{
    public function findNonValidated()
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.validated = false')
            ->addOrderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findValidated()
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.validated = true')
            ->addOrderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findAssociateTimeSheet($id)
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.associate', 'a')
            ->leftJoin('t.mission', 'm')
            ->where('m.status = :stat')
            ->andwhere('a.id = :id')
            ->setParameter(':id', $id)
            ->setParameter(':stat', 'en cours')
            ->orderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findTimeSheets($startDate, $endDate)
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.day <= :endDate')
            ->andWhere('t.day >= :startDate')
            ->setParameter(':startDate', $startDate)
            ->setParameter(':endDate', $endDate)
            ->getQuery()
            ->getResult();

        return $result;
    }

}

