<?php

namespace MP\TimeSheetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeSheetRepository extends EntityRepository
{
    public function findNonValidated()
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.validated = false')
            ->addOrderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findValidated()
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.validated = true')
            ->addOrderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findAssociateTimeSheet($id)
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.associate', 'a')
            ->leftJoin('t.mission', 'm')
            ->where('m.status = :stat')
            ->andwhere('a.id = :id')
            ->setParameter(':id', $id)
            ->setParameter(':stat', 'en cours')
            ->orderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    /**
     * Select TimeSheets Between two dates
     */

    public function findTimeSheets($startDate, $endDate, $id)
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.associate', 'a')
            ->leftJoin('t.mission', 'm')
            ->where('m.status = :stat')
            ->setParameter(':stat', 'en cours')
            ->andwhere('a.id = :id')
            ->setParameter(':id', $id)
            ->andwhere('t.day <= :endDate')
            ->setParameter(':endDate', $endDate, \Doctrine\DBAL\Types\Type::DATETIME)
            ->andWhere('t.day >= :startDate')
            ->setParameter(':startDate', $startDate, \Doctrine\DBAL\Types\Type::DATETIME)
            ->orderBy('t.day')
            ->getQuery()
            ->getResult();

        return $result;
    }

    public function findManagerTimeSheets($id)
    {
        $result = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.mission', 'm')
            ->leftJoin('m.associate', 'ma')
            ->leftJoin('ma.associate', 'a')
            ->where('a.id = :id')
            ->setParameter(':id', $id)
            ->andWhere('t.validated = false')
            ->getQuery()
            ->getResult();

        return $result;
    }

}

